# #file: noinspection AppEngineThreadsafe
# # https://cloud.google.com/appengine/docs/standard/python3/config/appref?hl=pt-br
# #env ALWAYS STANDARD! NEVER FLEXIBLE

# runtime: nodejs20
# instance_class: F1
# service: api-staging

# entrypoint: npm run start-staging

# env_variables:
#   TYPEORM_CONNECTION: postgres
#   TYPEORM_HOST: 10.149.96.3
#   TYPEORM_USERNAME: postgres
#   TYPEORM_PASSWORD: "Arx65Z+bAI#TU@a"
#   TYPEORM_DATABASE: homolog
#   TYPEORM_PORT: 5432
#   TYPEORM_ENTITIES: src/Models/*.ts
#   TYPEORM_ENTITIES_DIR: src/Models
#   TYPEORM_JWT_SECRET: "JFiusDAfhPAGAAdB83FateejteIGyugVC27QOgjaogjaoagea#24g0aaVF7V7DSBC326cdv@3234#$*ac6cdf6CF7SAB74FV"
#   APP_PORT: 8080
#   APP_UTIL_API_URL: "https://staging.causaganha.app/utils-api"
#   APP_URL: "https://homolog.causaganha.app"
#   APP_API_SUFFIX: "/api-v1-9cdff66dfc3dce1a586700d77a4cd2282d33b6bb"
#   APP_CDN_SUFFIX: "staging"
#   APP_FACEBOOK_REDIRECT_URI: "https://homolog.causaganha.app/auth/facebook"
#   APP_GOOGLE_REDIRECT_URI: "https://homolog.causaganha.app/auth/google"
#   GOOGLE_APPLICATION_CREDENTIALS: "./cdn.json"
#   GOOGLE_AI_CREDENTIALS: "./causa-ganha-app-8c09029c4daf.json" 
#   AI_AGENT: 'projects/causa-ganha-app/locations/global/agents/18a607c6-18b4-4ebd-985b-10fa6f786c53'
#   APP_URL_API: "https://staging.causaganha.app/api-v1-9cdff66dfc3dce1a586700d77a4cd2282d33b6bb"
#   CONFIG_ORIGIN: staging

# error_handlers:
#   - file: /static/default_error.html

#   - error_code: over_quota
#     file: /static/over_quota.html

# handlers:
#   - url: /*
#     secure: always
#     script: auto


# automatic_scaling:
#   min_idle_instances: automatic
#   max_idle_instances: automatic
#   min_pending_latency: automatic
#   max_pending_latency: automatic
#   target_cpu_utilization: 0.90
#   min_instances: 1

# vpc_access_connector:
#   name: projects/causa-ganha-app/locations/us-central1/connectors/causa-ganha-app-connector
#   egress_setting: private-ranges-only
